### ISSUE TITLE
Is there a way to keep an "admin" page type and use this?

### ISSUE THREAD

**Issue by CodeCommander** [symphonists/content_type_mappings#10]
I'd like to use this plugin for a csv templated page I built that is accessible only to admins, but because I need to set the page type to "csv" I cannot have the page also be "admin". Is there a way to have the page be restricted to just admins, but also get the csv content type?

**Comment by michael-e** [comment]
Generally you can use multiple page types. What's the problem in this case?

**Comment by CodeCommander** [comment]
Wow, I didn't realize you can use multiple page types separated by a comma. That works perfect, thanks!

**Comment by CodeCommander** [comment]
Is there a repo to recommend changes to the documentation? It would be good to mention this on this page: https://www.getsymphony.com/learn/concepts/view/page-types/

**Comment by michael-e** [comment]
Something you should know: If you click on an existing page type (in the list below the field), Symphony automatically adds/removes it from the list in the field.

I am not sure of there is a repo for these docs, sorry… But you might either ask in the Gitter chat or open an issue in the Symphony repo – @nitriques will know what can be done.

**Comment by CodeCommander** [comment]
Oh, I see! Nice. I didn't have a csv type yet so I just typed it in and didn't realize that.

**Comment by michael-e** [comment]
Sure, it's an auto-generated list of all default page types plus "actively used" page types. You can add any string as a new page type — but it will only have an effect if it's either known by the core or by an extension.

I guess I can close this issue?

**Comment by CodeCommander** [comment]
Yes. Go ahead. Thank you.
