### ISSUE TITLE
GitHub link wrong

### ISSUE THREAD

**Issue by wdebusschere** [symphonists/content_type_mappings#8]
https://github.com/symphonycms/content_type_mappings
https://github.com/symphonists

**Comment by nitriques** [comment]
Where ?

**Comment by wdebusschere** [comment]
in the extension.meta.xml. Created a PR: https://github.com/symphonists/content_type_mappings/pull/9

**Comment by nitriques** [comment]
Nevermind I've found it and fixed it ;)
